// components/tabs/index.vue
<template>
  <div class="share-tabs">
    <ad-button
      ad-type="main"
      label="Received"
      :text="activeTab !== 'received'"
      class="tab-button"
      @click="$emit('update:activeTab', 'received')"
    />
    <ad-button
      ad-type="main"
      label="Sent"
      :text="activeTab !== 'sent'"
      class="tab-button"
      @click="$emit('update:activeTab', 'sent')"
    />
  </div>
</template>

<script setup lang="ts">
import type { ShareTabType } from 'nucleify'

defineProps<{
  activeTab: ShareTabType
}>()

defineEmits<{
  'update:activeTab': [tab: ShareTabType]
}>()
</script>

<style lang="scss">
@import 'index';
</style>

// components/tabs/index.tsx
'use client'

import type { JSX } from 'react'

import type { ShareTabType } from 'nucleify'
import { AdButton } from 'nucleify'

import './_index.scss'

type NucShareTabsProps = {
  activeTab: ShareTabType
  onUpdateActiveTab: (tab: ShareTabType) => void
}

export function NucShareTabs({
  activeTab,
  onUpdateActiveTab,
}: NucShareTabsProps): JSX.Element {
  return (
    <div className="share-tabs">
      <AdButton
        nuiType="main"
        label="Received"
        text={activeTab !== 'received'}
        className="tab-button"
        onClick={() => onUpdateActiveTab('received')}
      />
      <AdButton
        nuiType="main"
        label="Sent"
        text={activeTab !== 'sent'}
        className="tab-button"
        onClick={() => onUpdateActiveTab('sent')}
      />
    </div>
  )
}
