// components/dialog/index.tsx
'use client'

import type { JSX } from 'react'

import type { NucShareDialogInterface } from 'nucleify'
import {
  AdHeading,
  NucDialog,
  NucShareCheckbox,
  useShareDialog,
} from 'nucleify'

import './_index.scss'

export function NucShareDialog(props: NucShareDialogInterface): JSX.Element {
  const {
    friends,
    selectedEntities,
    loading,
    isConfirmDisabled,
    handleShare,
    handleCancel,
    toggleFriend,
    isFriendSelected,
  } = useShareDialog(props)

  const { adType, visible } = props

  return (
    <NucDialog
      entity={adType as ObjectNameType}
      visible={!!visible}
      modal
      draggable={false}
      title="Share Entities"
      action={'share' as ActionType}
      cancelButtonLabel="Cancel"
      confirmButtonLabel="Share"
      confirmButtonDisabled={isConfirmDisabled}
      confirm={async () => {
        await handleShare()
      }}
      close={() => {
        handleCancel()
      }}
      onHide={handleCancel}
    >
      <div className="share-dialog">
        <div className="share-dialog-content">
          {selectedEntities.length > 0 ? (
            <div className="share-dialog-info">
              Selected count: {selectedEntities.length}
            </div>
          ) : (
            <div className="share-dialog-warning">
              No items selected. Select items in the table first.
            </div>
          )}

          <div className="share-dialog-subtitle">
            <AdHeading tag={5} text="Select Users" />
          </div>

          <div className="share-dialog-friends">
            {loading ? (
              <p className="share-dialog-loading">Loading users...</p>
            ) : (
              friends.map((friend) => (
                <label key={friend.id} className="share-dialog-friend">
                  <NucShareCheckbox
                    adType={adType}
                    checked={isFriendSelected(friend.id)}
                    onToggle={() => toggleFriend(friend.id)}
                  />
                  <div className="share-dialog-friend-info">
                    <span className="share-dialog-friend-name">
                      {friend.name}
                    </span>
                    {friend.email ? (
                      <span className="share-dialog-friend-email">
                        {friend.email}
                      </span>
                    ) : null}
                  </div>
                </label>
              ))
            )}
          </div>
        </div>
      </div>
    </NucDialog>
  )
}

// components/dialog/index.vue
<template>
  <nuc-dialog
    :entity="props.adType"
    :visible="props.visible && !loading"
    :modal="true"
    :draggable="false"
    title="Share Entities"
    action="share"
    cancel-button-label="Cancel"
    confirm-button-label="Share"
    :confirm-button-disabled="isConfirmDisabled"
    :confirm="handleShare"
    :close="handleCancel"
    class="share-dialog"
    @update:visible="emits('update:visible', $event)"
  >
    <template #content>
      <div class="share-dialog-content">
        <div v-if="selectedEntities.length > 0" class="share-dialog-info">
          Selected count: {{ selectedEntities.length }}
        </div>
        <div v-else class="share-dialog-warning">
          No items selected. Select items in the table first.
        </div>

        <ad-heading
          :tag="5"
          text="Select Users"
          class="share-dialog-subtitle"
        />

        <div class="share-dialog-friends">
          <label
            v-for="friend in friends"
            :key="friend.id"
            class="share-dialog-friend"
          >
            <ad-checkbox
              :ad-type="props.adType"
              :model-value="isFriendSelected(friend.id)"
              :binary="true"
              @change="toggleFriend(friend.id)"
            />
            <div class="share-dialog-friend-info">
              <span class="share-dialog-friend-name"> {{ friend.name }} </span>
              <span v-if="friend.email" class="share-dialog-friend-email">
                {{ friend.email }}
              </span>
            </div>
          </label>
        </div>
      </div>
    </template>
  </nuc-dialog>
</template>

<script setup lang="ts">
import type { NucShareDialogInterface } from 'nucleify'
import { useShareDialog } from 'nucleify'

const props = defineProps<NucShareDialogInterface>()
const emits = defineEmits(['update:visible'])

const {
  friends,
  selectedEntities,
  loading,
  isConfirmDisabled,
  handleShare,
  handleCancel,
  toggleFriend,
  isFriendSelected,
} = useShareDialog(props, emits)
</script>

<style lang="scss">
@import 'index';
</style>
