// components/requests-list/index.tsx
'use client'

import type { JSX } from 'react'

import type { ShareRequestInterface } from 'nucleify'
import { AdButton, AdTag, NucShareRequestsItem } from 'nucleify'

import './_index.scss'

type NucShareRequestsListProps = {
  requests?: ShareRequestInterface[]
  isReceived?: boolean
  onAccept?: (id: number) => void
  onReject?: (id: number) => void
  onCancel?: (id: number) => void
}

export function NucShareRequestsList({
  requests = [],
  isReceived = false,
  onAccept,
  onReject,
  onCancel,
}: NucShareRequestsListProps): JSX.Element {
  if (requests.length === 0) {
    return (
      <div className="share-requests-list">
        <div className="share-requests-list-empty">
          <p>No share requests</p>
        </div>
      </div>
    )
  }

  return (
    <div className="share-requests-list">
      {requests.map((request) => (
        <NucShareRequestsItem
          key={request.id}
          request={request}
          isReceived={isReceived}
          actions={
            isReceived ? (
              <>
                <AdButton
                  nuiType="main"
                  icon="prime:check"
                  text
                  rounded
                  onClick={() => onAccept?.(request.id)}
                />
                <AdButton
                  icon="prime:times"
                  text
                  rounded
                  severity="danger"
                  onClick={() => onReject?.(request.id)}
                />
              </>
            ) : request.status === 'pending' ? (
              <AdButton
                nuiType="main"
                icon="prime:times"
                text
                rounded
                severity="secondary"
                onClick={() => onCancel?.(request.id)}
              />
            ) : (
              <AdTag
                value={request.status}
                severity={request.status === 'accepted' ? 'success' : 'danger'}
              />
            )
          }
        />
      ))}
    </div>
  )
}

// components/requests-list/index.vue
<template>
  <div class="share-requests-list">
    <div v-if="requests.length === 0" class="share-requests-list-empty">
      <p>No share requests</p>
    </div>
    <template v-else>
      <nuc-share-requests-item
        v-for="request in requests"
        :key="request.id"
        :request="request"
        :is-received="isReceived"
      >
        <template #actions>
          <template v-if="isReceived">
            <ad-button
              nui-type="main"
              icon="prime:check"
              text
              rounded
              @click="$emit('accept', request.id)"
            />
            <ad-button
              icon="prime:times"
              text
              rounded
              severity="danger"
              @click="$emit('reject', request.id)"
            />
          </template>
          <template v-else>
            <ad-button
              v-if="request.status === 'pending'"
              nui-type="main"
              icon="prime:times"
              text
              rounded
              severity="secondary"
              @click="$emit('cancel', request.id)"
            />
            <ad-tag
              v-else
              :value="request.status"
              :severity="request.status === 'accepted' ? 'success' : 'danger'"
            />
          </template>
        </template>
      </nuc-share-requests-item>
    </template>
  </div>
</template>

<script setup lang="ts">
import type { ShareRequestInterface } from 'nucleify'

interface Props {
  requests?: ShareRequestInterface[]
  isReceived?: boolean
}

withDefaults(defineProps<Props>(), {
  requests: () => [],
  isReceived: false,
})

defineEmits<{
  accept: [id: number]
  reject: [id: number]
  cancel: [id: number]
}>()
</script>

<style lang="scss">
@import 'index';
</style>
