// components/popover/index.vue
<template>
  <div class="share-popover-container">
    <ad-heading :tag="3" text="Share Requests" class="share-popover-header" />

    <div class="share-popover-content">
      <nuc-share-tabs
        :active-tab="activeTab"
        @update:active-tab="activeTab = $event"
      />

      <nuc-share-requests-list
        v-if="activeTab === 'received'"
        :requests="receivedRequests"
        :is-received="true"
        @accept="handleAccept"
        @reject="handleReject"
      />

      <nuc-share-requests-list
        v-if="activeTab === 'sent'"
        :requests="sentRequests"
        @cancel="handleCancel"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { ShareTabType } from 'nucleify'
import { useShareRequests } from 'nucleify'

const activeTab = ref<ShareTabType>('received')

const {
  received,
  sent,
  getReceived,
  getSent,
  acceptRequest,
  rejectRequest,
  cancelRequest,
} = useShareRequests()

const receivedRequests = computed(() => received.value ?? [])
const sentRequests = computed(() => sent.value ?? [])

watch(activeTab, (tab) => {
  if (tab === 'received') void getReceived()
  if (tab === 'sent') void getSent()
})

async function handleAccept(id: number): Promise<void> {
  await acceptRequest(id)
}

async function handleReject(id: number): Promise<void> {
  await rejectRequest(id)
}

async function handleCancel(id: number): Promise<void> {
  await cancelRequest(id)
}
</script>

<style lang="scss">
@import 'index';
</style>

// components/popover/index.tsx
'use client'

import { type JSX, useEffect, useRef, useState } from 'react'

import type { ShareRequestInterface, ShareTabType } from 'nucleify'
import { AdHeading, NucShareRequestsList, NucShareTabs } from 'nucleify'

import './_index.scss'

export interface NucSharePopoverProps {
  received: ShareRequestInterface[]
  sent: ShareRequestInterface[]
  getReceived: () => Promise<void>
  getSent: () => Promise<void>
  acceptRequest: (id: number) => Promise<void>
  rejectRequest: (id: number) => Promise<void>
  cancelRequest: (id: number) => Promise<void>
}

export function NucSharePopover({
  received,
  sent,
  getReceived,
  getSent,
  acceptRequest,
  rejectRequest,
  cancelRequest,
}: NucSharePopoverProps): JSX.Element {
  const [activeTab, setActiveTab] = useState<ShareTabType>('received')
  const previousTab = useRef(activeTab)

  useEffect(() => {
    if (previousTab.current === activeTab) return
    previousTab.current = activeTab
    if (activeTab === 'received') void getReceived()
    if (activeTab === 'sent') void getSent()
  }, [activeTab, getReceived, getSent])

  return (
    <div className="share-popover-container">
      <div className="share-popover-header">
        <AdHeading tag={3} text="Share Requests" />
      </div>

      <div className="share-popover-content">
        <NucShareTabs activeTab={activeTab} onUpdateActiveTab={setActiveTab} />

        {activeTab === 'received' ? (
          <NucShareRequestsList
            requests={received}
            isReceived
            onAccept={(id) => void acceptRequest(id)}
            onReject={(id) => void rejectRequest(id)}
          />
        ) : null}

        {activeTab === 'sent' ? (
          <NucShareRequestsList
            requests={sent}
            onCancel={(id) => void cancelRequest(id)}
          />
        ) : null}
      </div>
    </div>
  )
}
